location: durham

evaluation:
  enable:
    grocery: 1
    bus: 0
    safety: 0

  threshold:
    grocery:
      metric: distance_to_nearest
      better: lower # lower distance is better
      min: 0.3  # gets a max score if 0.3 miles or less
      max: 1.0  # gets a 0 score if more than 1.0 miles, in between it is in linear
    bus:
      metric: distance_to_nearest
      better: lower # lower distance is better
      min: 0.3  # gets a max score if 0.3 miles or less
      max: 1.0  # gets a 0 score if more than 1.0 miles, in between it is in linear
    safety:
      metric: distance_to_nearest
      better: lower # lower distance is better
      min: 0.3  # gets a max score if 0.3 miles or less
      max: 1.0  # gets a 0 score if more than 1.0 miles, in between it is in linear

  weight:
    grocery: 1.0
    bus: 0.0
    safety: 0.0

grocery:
  # Note that some of these are required to be in the include section because they do not have the proper google places tagging
  # (eg. Kroger has 'grocery_or_supermarket' which is a deprecated tag and does not have the proper 'supermarket' tag)
  include:
    Food Lion: 1
    Kroger: 1
    Walmart: 1
    Walmart Supercenter: 1
    Walmart Neighborhood Market: 1
    Supertarget: 1
    ALDI: 1
    Lidl: 1
    Publix: 1
    Lowes Foods: 1
    Compare Foods: 1
    Save-A-Lot: 1
    Food World: 1
  exclude:
    Harris Teeter: 1
    Whole Foods: 1
    Harris Teeter: 1
    Trader Joe's: 1
    Sam's Club: 1
    Durham Co-Op: 1
    Whole Foods Market: 1
    Family Dollar: 1
    A&C SUPERMARKET EQUIPMENT: 1
    tobacco & vape: 1
    The Fresh Market: 1
    los primos market alston: 1
  style:
    color: '000000'
    icon: shopping cart

bus:
  include: {}
  exclude: {}
  style: {}

safety:
  include: {}
  exclude: {}
  style: {}
