location: durham

evaluation:
  enable:
    grocery: 1
    bus: 0
    safety: 0

  threshold:
    grocery:
      metric: distance_to_nearest
      better: lower # lower distance is better
      min: 0.3  # gets a max score if 0.3 miles or less
      max: 1.0  # gets a 0 score if more than 1.0 miles, in between it is in linear
    bus:
      metric: distance_to_nearest
      better: lower # lower distance is better
      min: 0.3  # gets a max score if 0.3 miles or less
      max: 1.0  # gets a 0 score if more than 1.0 miles, in between it is in linear
    safety:
      metric: distance_to_nearest
      better: lower # lower distance is better
      min: 0.3  # gets a max score if 0.3 miles or less
      max: 1.0  # gets a 0 score if more than 1.0 miles, in between it is in linear

  weight:
    grocery: 1.0
    bus: 0.0
    safety: 0.0

grocery:
  include:
    Food Lion: 1
    Kroger: 1
  exclude:
    Harris Teeter: 1
  style:
    color: '000000'
    icon: shopping cart

bus:
  include: {}
  exclude: {}
  style: {}

safety:
  include: {}
  exclude: {}
  style: {}
