location: durham

### Parameters for finding things
find:
  bus:
    include:
      godurhamtransit.org: 1

  grocery:
    # Note that some of these are required to be in the include section because they do not have the proper google places tagging
    # (eg. Kroger has 'grocery_or_supermarket' which is a deprecated tag and does not have the proper 'supermarket' tag)
    include:
      Food Lion: 1
      Kroger: 1
      Walmart: 1
      Walmart Supercenter: 1
      Walmart Neighborhood Market: 1
      Supertarget: 1
      ALDI: 1
      Lidl: 1
      Publix: 1
      Lowes Foods: 1
      Compare Foods: 1
      Save-A-Lot: 1
      Food World: 1
    exclude:
      Harris Teeter: 1
      Whole Foods: 1
      Trader Joe's: 1
      Sam's Club: 1
      Durham Co-Op: 1
      Whole Foods Market: 1
      Family Dollar: 1
      A&C SUPERMARKET EQUIPMENT: 1
      tobacco & vape: 1
      The Fresh Market: 1
      Family Fare Collaboration & Support Center: 1
      True World Foods: 1

  resources:
    include:
      801 Gilbert St, Durham, NC 27701:
        name: World Relief Durham
      414 E Main St, Durham, NC 27701:
        name: NC Division of Social Services
      112 S Duke St \# 4B, Durham, NC 27701:
        name: Church World Service
      515 W Pettigrew St, Durham, NC 27701:
        name: Durham Station
      2301 Erwin Rd, Durham, NC 27710:
        name: Duke University Hospital
      3643 N Roxboro St, Durham, NC 27704:
        name: Duke Regional Hospital
    exclude: {}

  employment:
    include: {}
    exclude:
      # lodging exclusions
      Eno Cottage: 1
      Pet Spa: 1
      segura: 1
      Sterling Townhomes: 1

      # supermarket exclusions
      Sam's Club: 1
      Durham Co-Op: 1
      A&C SUPERMARKET EQUIPMENT: 1
      tobacco & vape: 1
      Family Fare Collaboration & Support Center: 1
      True World Foods: 1

  safety: {}

### Parameters for evaluating things
evaluation:
  enable:
    bus: 1
    grocery: 1
    resources: 0
    employment: 0
    safety: 0

  value:
    bus:
      selection:
        type: nearest
        nearest: 1
        final: average
      function:
      - point: [0.0,1.0]
      - linear
      - point: [0.25,0.8]
      - linear
      - point: [0.75,0.0]
      - linear
      - point: [16.0,0.0]
    grocery:
      selection:
        type: nearest
        nearest: 1
        final: average
      function:
      - point: [0.0,1.0]
      - linear
      - point: [0.25,0.95]
      - linear
      - point: [0.75,0.70]
      - linear
      - point: [1.25,0.20]
      - exp: [6.4,-2.7726]
    resources:
      selection:
        type: nearest
        nearest: all
        final: average
      function:
      - exp2: [1.0,-0.02]
    employment:
      selection:
        type: nearest
        nearest: 10
        final: average
      function:
      - point: [0.0,1.0]
      - linear
      - point: [0.5,0.95]
      - linear
      - point: [3.0,0.2]
      - exp: [12.8, -1.386] 
    safety:
      selection:
        type: evaluated

  final:
    mul:
      - bus
      - weighted_sum:
          grocery: 1.0
          resources: 0.0
          employment: 0.0
          safety: 0.0

### Parameters for visualizing things
visualization:
  bus:
    style:
      color: '0000CC'
      icon: bus

  grocery:
    style:
      color: '000000'
      icon: shopping cart

  resources:
    style: {}

  employment:
    style: {}

  safety:
    style: {}
